config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  resources :quote_categories
  resources :categories
  resources :quotes
  resources :authors
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/about', to: 'about#index'
  get 'search', to: 'search#index'
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout #Chat GPT Solution
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex' 
  get '/your-quotes', to: 'home#uquotes'
  get '/new-quote', to: 'quote#new'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :quotes, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_login, except: [:new, :create]

  # GET /users or /users.json
  def index
    if logged_in? && is_administrator? 
      @users = User.all
    elsif logged_in? && !is_administrator? 
      redirect_to userhome_path
    else
      flash[:error] = "You are not authorised to access this resource" 
      redirect_to login_path
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.html { redirect_to login_path, notice: "Sign up successful. Please log in." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:status, :f_name, :l_name, :email, :admin, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row" style="padding: 15px;">
    <div class="col">
      <%= form.text_field :f_name, placeholder: 'First Name', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
    </div>
    <div class="col">
      <%= form.text_field :l_name, placeholder: 'Last Name', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
    </div>
  </div>

  <div class="form-group" style="padding: 15px;">

  <%= form.text_field :email, placeholder: 'E-Mail', class: 'form-control', readonly: (logged_in? && is_administrator?) %>
  </div>

  <div>
  <%= form.hidden_field :status, value:"Active" %>
  </div>
  
  <div class="row" style="padding: 15px;">
    <div class="col"><hr></div>
    <div class="col-auto"></div>
  </div>

  <div class="form-group" style="padding: 15px;">
  <%= form.password_field :password, placeholder: user.password_digest.present? ? 'Password set' : 'Choose a strong password', class: 'form-control', readonly:
  (logged_in? && is_administrator?) %>
  </div>

  <div class="form-group" style="padding: 15px;">
    <% if logged_in? && is_administrator? %> 
      <%= form.label :admin do %> Admin Role
        <%= form.check_box :admin %>
      <% end %>
    <% else %>
      <%= form.hidden_field :is_admin, value: false %> 
    <% end %>  
  </div> 

  <div class="form-group" style="padding: 15px;">
    <% if logged_in? && is_administrator? %> 
      <%= form.select :status, ['Active', 'Suspended', 'Banned'], {}, class: 'formcontrol' %>
    <% elsif logged_in? && !is_administrator? %>
      <%= form.hidden_field :status %> 
    <% else %>
      <%= form.hidden_field :status, value: "Active" %>
    <% end %>  
  </div> 

  <div class="container" style="padding-top:40px";>
  <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="my-4">
  
  <div class="mb-3">
    <label class="form-label"><strong>First Name:</strong></label>
    <div><%= user.f_name %></div>
  </div>

  <div class="mb-3">
    <label class="form-label"><strong>Last Name:</strong></label>
    <div><%= user.l_name %></div>
  </div>

  <div class="mb-3">
    <label class="form-label"><strong>E-mail:</strong></label>
    <div><%= user.email %></div>
  </div>

  <div class="mb-3">
    <label class="form-label"><strong>Current Password:</strong></label>
    <span class="text-danger">ENCRYPTED</span>
  </div>

  <div class="mb-3">
    <label class="form-label"><strong>Account Type:</strong></label>
    <div>
      <% if user.admin %>
        <span>Administrator</span>
      <% else %>
        <span>Standard User</span>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <label class="form-label"><strong>Status:</strong></label>
    <div><%= user.status %></div>
  </div>

</div>

app/views/users/edit.html.erb
<div style="padding-top: 10px;"> 
  <% if logged_in? && is_administrator? %> 
    <h3>Update User Details</h3> 
  <% else %> 
    <h3>Update Your Details</h3> 
  <% end %>
</div> 

<%= render "form", user: @user %> 
<% if logged_in? && is_administrator? %>
  <div style="padding-top: 10px;">
    <div>
      <!--Replaced with buttons, just looks better than links, ms/mr/mt is for spacing-->
      <a href="<%= users_path %>" class="btn btn-outline-secondary ms-2 mt-5" style="margin-right:20px;">Back to Users</a>
      <a href="<%= user_path(@user) %>" class="btn btn-warning mr-5 mt-5">Show User Details</a>
    </div> 
  </div>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <!--Shows all users in the database on bootstrap cards-->
    <div class= "container" style="padding-bottom: 30px;">
    <div class="card" style="width: 32rem;">
      <div class="card-body">
        <h5 class="card-title"><%= user.f_name%> <%= user.l_name%> 
          <!--Puts an admin flag next to the name if the user is an admin-->
          <% if user.admin %>
            <span class="badge text-bg-warning">Admin</span>
          <% end %></h5>
        <p class="card-text">
        <strong>Email:</strong>
        <%= user.email %></br>
        <strong>Current Password: </strong><span class="text-danger">ENCRYPTED</span> 
        <% user.password_digest %>
        </p>
        <a href="<%= user_path(user) %>" class="btn btn-primary">Show Details</a>
        
      </div>
    </div>
    </div>
  <% end %>
</div>

<!--% link_to "New user", new_user_path %-->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

<br>

<div>
  <!--%= link_to "Back to users", users_path %-->
</div>

app/views/users/show.html.erb
<h1>User Details</h1>
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div style="margin-top:40px;">

  <a href="<%= users_path %>" class="btn btn-outline-secondary" style="margin-right:20px;">Back to Users</a>
  <a href="<%= edit_user_path(@user) %>" class="btn btn-warning mr-5">Edit User</a>
  
  <div style="padding-top: 50px">
  <%= button_to "Delete User", @user, method: :delete, class: "btn btn-danger"%>
  </div>
</div>