config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  resources :quote_categories
  resources :categories
  resources :quotes
  resources :authors
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/about', to: 'about#index'
  get 'search', to: 'search#index'
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout #Chat GPT Solution
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex' 
  get '/your-quotes', to: 'home#uquotes'
  get '/new-quote', to: 'quote#new'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :quotes, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :quote_categories
    has_many :quotes, through: :quote_categories
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user
  belongs_to :author
  has_many :quote_categories
  has_many :categories, through: :quote_categories, dependent: :destroy
  accepts_nested_attributes_for :quote_categories, reject_if: :all_blank, allow_destroy: true
end

app/models/quote_category.rb
class QuoteCategory < ApplicationRecord
  belongs_to :quote
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :quotes, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # Gets the most recently posted quotes,top down
    @quotes = Quote.order(pub_date: :desc).take(5)
  end

  def uquotes
    # Gets the most recent quotes from the user, top down
    @quotes = Quote.where(user_id: session[:user_id]).reverse()
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]
  before_action :require_login, except: [:index, :show] # Only requires log in for all children except index and show

  # GET /quotes or /quotes.json
  def index
    @quotes = current_user.quotes
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
    1.times { @quote.quote_categories.build }
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    puts "Quote Params: #{quote_params.inspect}"
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to "/your-quotes", notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:quote_text, :public, :user_com, :pub_date, :user_id, :author_id, quote_categories_attributes: [:id, :category_id])
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    # Stolen from the workshop
    quote_query = params[:quote_query] 
    if quote_query.present? 
      @quotematch = Quote.all.where("quotes.quote_text LIKE ?", "%#{quote_query}%").distinct 
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_login, except: [:new, :create]

  # GET /users or /users.json
  def index
    if logged_in? && is_administrator? 
      @users = User.all
    elsif logged_in? && !is_administrator? 
      redirect_to userhome_path
    else
      flash[:error] = "You are not authorised to access this resource" 
      redirect_to login_path
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.html { redirect_to login_path, notice: "Sign up successful. Please log in." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:status, :f_name, :l_name, :email, :admin, :password)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<!--Slightly modified from the bootstrap example, search bar removed-->
<nav class="navbar bg-dark border-bottom border-body navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">myQuote</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'About Us', about_path, class:"nav-link" %>
        </li>
        <li><a class="nav-link" href="/search">Search</a></li>

        <!--Standard User Drop Down (Profile)-->
        <% if logged_in? && !is_administrator? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
            <%= link_to "My Account", userhome_path, class:"dropdown-item" %> 
            <%= link_to "My Quotes", your_quotes_path, class:"dropdown-item" %> 
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Add quote", new_quote_path, class:"dropdown-item" %> 
            </li>
            </ul>
          </li>
        <% end %>

        <!--Admin drop down-->
        <% if logged_in? && is_administrator? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Admin
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Admin Home", admin_path, class:"dropdown-item" %></li>
              <li><a class="dropdown-item" href="/users">Manage Users</a></li>              
            </ul>
          </li>
        <% end %>
      </ul>

      <!--Moves these links to the right of the nav bar-->
      <ul class="navbar-nav mes-auto ms-right mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item">
            <li><%= link_to 'Sign Out',logout_path, method: :delete, class:"nav-link" %></li>
          </li>
        <% else %>
          <li class="nav-item">
            <li><%= link_to 'Sign Up', new_user_path, class:"nav-link" %></li>
          </li>
          <li class="nav-item">
            <li><%= link_to 'Sign In', login_path, class:"nav-link" %></li>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyQuote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <!--%= stylesheet_link_tag "application", "data-turbo-track": "reload" %-->
    <!--%= javascript_importmap_tags %-->
  </head>

  <body>
    <!--Makes the background dark, got sick of burning my eyes,-->
    <!--i probably didn't implement it properly, but it gets it 90% of the time-->
    <div class="text-bg-dark p-5">
      <div class="container" style="margin-top:20px;">
        <%= render 'layouts/header' %>
          <div class="container" style="margin-top:80px;">
            <%= yield %>
          </div> 
      <div class="container" style="margin-top:600px;"></div>
      </div>
    </div>
  </body>
</html>